services:
  api:
    build: .
    container_name: projectlab-api
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=Laboratory;Uid=root;Pwd=mestre;
    depends_on:
      - db
    networks:
      - projectlab-network

  db:
    image: mysql:8.0
    container_name: projectlab-db
    environment:
      - MYSQL_ROOT_PASSWORD=mestre
      - MYSQL_DATABASE=Laboratory
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - projectlab-network

volumes:
  mysql_data:

networks:
  projectlab-network:
    driver: bridge